package org.fsystem.financesystem.model;

public enum Icon {
    AIRPLANE, APPAREL, BABY, BANK, BEACH, BED, BIKE, BITCOIN, BOOK, CAKE, CALCULATE, CAMERA, CAR, CASH, CHAT,
    CHURCH, CLOUD, COFFEE, CREDIT_CARD, CRIB, DENTIST, DESKTOP, DIRECTIONS_BUS, DOCTOR, ECG_HEART, FAMILY, FINANCE,
    FLAG, FOREST, GAMES, GAS_STATION, GYM, HANDBAG, HEART, HOUSE, KEY, LIGHTBULB, LIGHTING, LIST_ALT, MAIL, MEDICAL,
    MENU_BOOK, MIC, MONITORING, MORE_HORIZ, MOVIE, MUSIC, NOTE, PAID, PAINT, PARK, PENCIL, PET, PHONE, PRESENT, PRINTER,
    REFRIGERATOR, RUN, SCHOOL, SHOPPING_BASKET, SHOPPING_CART, SMILE, SOCCER, TEXT, THUMB_UP, TRENDING_DOWN, TRENDING_UP,
    TRIPS, VERIFIED, WORK, WORLD
}
