package org.fsystem.financesystem.models.category;

public enum CategoryIcon {
    AIRPLANE("airplane.png"),
    APPAREL("apparel.png"),
    BABY("baby.png"),
    BANK("bank.png"),
    BEACH("beach.png"),
    BED("bed.png"),
    BIKE("bike.png"),
    BITCOIN("bitcoin.png"),
    BOOK("book.png"),
    CAKE("cake.png"),
    CALCULATE("calculate.png"),
    CAMERA("camera.png"),
    CAR("car.png"),
    CASH("cash.png"),
    CHAT("chat.png"),
    CHURCH("church.png"),
    CLOUD("cloud.png"),
    COFFEE("coffee.png"),
    CREDIT_CARD("credit_card.png"),
    CRIB("crib.png"),
    DENTIST("dentist.png"),
    DESKTOP("desktop.png"),
    DIRECTION_BUS("direction_bus.png"),
    DOCTOR("doctor.png"),
    ECG_HEART("ecg_heart.png"),
    FAMILY("family.png"),
    FINANCE("finance.png"),
    FLAG("flag.png"),
    FOREST("forest.png"),
    GAMES("games.png"),
    GAS_STATION("gas_station.png"),
    GYM("gym.png"),
    HANDBAG("handbag.png"),
    HEART("heart.png"),
    HOUSE("house.png"),
    KEY("key.png"),
    LIGHTBULB("lightbulb.png"),
    LIGHTING("lighting.png"),
    LIST_ALT("list_alt.png"),
    MAIL("mail.png"),
    MEDICAL("medical.png"),
    MENU_BOOK("menu_book.png"),
    MIC("mic.png"),
    MONITORING("monitoring.png"),
    MORE_HORIZ("more_horiz.png"),
    MOVIE("movie.png"),
    MUSIC("music.png"),
    NOTE("note.png"),
    PAID("paid.png"),
    PAINT("paint.png"),
    PARK("park.png"),
    PENCIL("pencil.png"),
    PET("pet.png"),
    PHONE("phone.png"),
    PRESENT("present.png"),
    PRINTER("printer.png"),
    REFRIGERATOR("refrigerator.png"),
    RUN("run.png"),
    SCHOOL("school.png"),
    SHOPPING_BASKET("shopping_basket.png"),
    SHOPPING_CART("shopping_cart.png"),
    SMILE("smile.png"),
    SOCCER("soccer.png"),
    TEXT("text.png"),
    THUMB_UP("thumb_up.png"),
    TRENDING_DOWN("trending_down.png"),
    TRENDING_UP("trending_up.png"),
    TRIPS("trips.png"),
    VERIFIED("verified.png"),
    WORK("work.png"),
    WORLD("world.png");

    private final String iconFile;

    CategoryIcon(String iconFile) {
        this.iconFile = iconFile;
    }

    public String getIconFile() {
        return iconFile;
    }
}
